### ISSUE TITLE
Reading/writing local files

### ISSUE THREAD

**Issue by angeloc-dl** [microsoft/python-in-excel#59]
Is it possible to use python to read or write local files ?

**Comment by keyur32** [comment]
Hi there, you can not due to security reasons, as the Python code can only access values referenced via the xl() function, and return values or images as a result of the Python formula: https://support.microsoft.com/en-us/office/data-security-and-python-in-excel-33cc88a4-4a87-485e-9ff9-f35958278327.

**Comment by angeloc-dl** [comment]
Which is the best practice to read a JSON file and use it with python for excel then?

**Comment by keyur32** [comment]
Good question - you can use PowerQuery to connect to JSON files, and then use that with Python in Excel.

[Connect to JSON or other sources](https://support.microsoft.com/en-us/office/import-data-from-data-sources-power-query-be4330b3-5356-486c-a168-b68e9e616f5a)


[Use Powerquery connections with Python in Excel](https://support.microsoft.com/en-us/office/use-power-query-to-import-data-for-python-in-excel-028dbcd4-76c5-4aa4-831d-0e211fefc0a2)
